# Generated by Django 5.2.11 on 2026-02-05 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mulvesdb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="文档标题")),
                ("file_path", models.CharField(max_length=1000, verbose_name="文件路径")),
                ("file_size", models.BigIntegerField(verbose_name="文件大小(字节)")),
                ("page_count", models.IntegerField(verbose_name="页数")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "已上传"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "处理失败"),
                        ],
                        default="uploaded",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "collection_name",
                    models.CharField(max_length=100, verbose_name="Milvus集合名称"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="处理完成时间"),
                ),
                (
                    "milvus_connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_documents",
                        to="mulvesdb.mulvesconnection",
                        verbose_name="Milvus连接",
                    ),
                ),
            ],
            options={
                "verbose_name": "PDF文档",
                "verbose_name_plural": "PDF文档",
                "db_table": "pdf_documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PDFChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.IntegerField(verbose_name="分块索引")),
                ("content", models.TextField(verbose_name="分块内容")),
                ("page_number", models.IntegerField(verbose_name="所在页码")),
                (
                    "vector_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="向量ID"
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        default="qwen", max_length=100, verbose_name="嵌入模型"
                    ),
                ),
                ("metadata", models.JSONField(default=dict, verbose_name="元数据")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="pdfloader.pdfdocument",
                        verbose_name="所属文档",
                    ),
                ),
            ],
            options={
                "verbose_name": "PDF分块",
                "verbose_name_plural": "PDF分块",
                "db_table": "pdf_chunks",
                "ordering": ["document", "chunk_index"],
            },
        ),
        migrations.AddIndex(
            model_name="pdfdocument",
            index=models.Index(
                fields=["status", "created_at"], name="pdf_documen_status_7fa9f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pdfdocument",
            index=models.Index(
                fields=["milvus_connection"], name="pdf_documen_milvus__0fd331_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pdfchunk",
            index=models.Index(
                fields=["document", "chunk_index"], name="pdf_chunks_documen_a89a02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pdfchunk",
            index=models.Index(
                fields=["vector_id"], name="pdf_chunks_vector__824e29_idx"
            ),
        ),
    ]
