# Generated by Django 5.2.11 on 2026-02-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pdfloader", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfdocument",
            name="file_hash",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="文件哈希值"
            ),
        ),
        migrations.AddIndex(
            model_name="pdfdocument",
            index=models.Index(fields=["file_hash"], name="pdf_documen_file_ha_123456_idx"),
        ),
    ]
