# Generated by Django 5.2.11 on 2026-02-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pdfloader", "0002_add_file_hash_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdfdocument",
            name="file_hash",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="文件哈希值",
            ),
        ),
    ]