# Generated by Django 5.2.11 on 2026-02-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pdfloader", "0003_make_file_hash_unique"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="pdfdocument",
            new_name="pdf_documen_file_ha_02a9f4_idx",
            old_name="pdf_documen_file_ha_123456_idx",
        ),
        migrations.AlterField(
            model_name="pdfdocument",
            name="file_hash",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="文件哈希值"
            ),
        ),
    ]
