# Generated by Django 5.2.11 on 2026-02-10 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mulvesdb", "0003_vectormetadata"),
        (
            "pdfloader",
            "0004_rename_pdf_documen_file_ha_123456_idx_pdf_documen_file_ha_02a9f4_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFCollectionConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="集合名称"),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "milvus_collection_name",
                    models.CharField(max_length=100, verbose_name="Milvus集合名称"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="是否默认集合"),
                ),
                (
                    "config_data",
                    models.JSONField(blank=True, default=dict, verbose_name="配置数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "milvus_connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_collection_configs",
                        to="mulvesdb.mulvesconnection",
                        verbose_name="Milvus连接",
                    ),
                ),
            ],
            options={
                "verbose_name": "PDF集合配置",
                "verbose_name_plural": "PDF集合配置",
                "db_table": "pdf_collection_configs",
                "ordering": ["-is_default", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="pdf_collect_is_acti_df8e25_idx"
                    ),
                    models.Index(
                        fields=["is_default"], name="pdf_collect_is_defa_664caa_idx"
                    ),
                    models.Index(
                        fields=["milvus_connection"],
                        name="pdf_collect_milvus__07f20d_idx",
                    ),
                ],
            },
        ),
    ]
