# Generated by Django 5.2.11 on 2026-02-05 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MulvesConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="连接名称"),
                ),
                ("host", models.CharField(max_length=255, verbose_name="主机地址")),
                ("port", models.IntegerField(default=5432, verbose_name="端口号")),
                ("database", models.CharField(max_length=100, verbose_name="数据库名")),
                ("username", models.CharField(max_length=100, verbose_name="用户名")),
                ("password", models.CharField(max_length=255, verbose_name="密码")),
                (
                    "ssl_enabled",
                    models.BooleanField(default=False, verbose_name="SSL启用"),
                ),
                (
                    "connection_timeout",
                    models.IntegerField(default=30, verbose_name="连接超时(秒)"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "Mulves连接配置",
                "verbose_name_plural": "Mulves连接配置",
                "db_table": "mulves_connections",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MulvesDataCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(max_length=255, unique=True, verbose_name="缓存键"),
                ),
                ("data", models.JSONField(verbose_name="缓存数据")),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "Mulves数据缓存",
                "verbose_name_plural": "Mulves数据缓存",
                "db_table": "mulves_data_cache",
                "indexes": [
                    models.Index(
                        fields=["cache_key"], name="mulves_data_cache_k_da217a_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="mulves_data_expires_5b1352_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MulvesQueryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_sql", models.TextField(verbose_name="SQL查询语句")),
                ("execution_time", models.FloatField(verbose_name="执行时间(毫秒)")),
                (
                    "result_count",
                    models.IntegerField(blank=True, null=True, verbose_name="结果数量"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="执行时间"),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="query_logs",
                        to="mulvesdb.mulvesconnection",
                        verbose_name="连接配置",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mulves查询日志",
                "verbose_name_plural": "Mulves查询日志",
                "db_table": "mulves_query_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["connection", "created_at"],
                        name="mulves_quer_connect_337c92_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="mulves_quer_created_cd91b2_idx"
                    ),
                ],
            },
        ),
    ]
