# Generated by Django 5.2.11 on 2026-02-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mulvesdb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChunkHashIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash_value", models.CharField(max_length=64, verbose_name="块哈希值")),
                ("content_length", models.IntegerField(verbose_name="内容长度")),
                (
                    "collection_name",
                    models.CharField(max_length=100, verbose_name="集合名称"),
                ),
                ("document_id", models.IntegerField(verbose_name="文档ID")),
                ("chunk_index", models.IntegerField(verbose_name="块索引")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(auto_now=True, verbose_name="最后访问时间"),
                ),
            ],
            options={
                "verbose_name": "块哈希索引",
                "verbose_name_plural": "块哈希索引",
                "db_table": "chunk_hash_indices",
                "indexes": [
                    models.Index(
                        fields=["hash_value"], name="chunk_hash__hash_va_909f0f_idx"
                    ),
                    models.Index(
                        fields=["collection_name"],
                        name="chunk_hash__collect_be4974_idx",
                    ),
                    models.Index(
                        fields=["document_id"], name="chunk_hash__documen_a7c2be_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="chunk_hash__created_8ec068_idx"
                    ),
                ],
                "unique_together": {("hash_value", "collection_name")},
            },
        ),
    ]
