# Generated by Django 5.2.11 on 2026-02-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mulvesdb", "0002_chunkhashindex"),
    ]

    operations = [
        migrations.CreateModel(
            name="VectorMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vector_id", models.CharField(max_length=100, verbose_name="向量ID")),
                (
                    "collection_name",
                    models.CharField(max_length=100, verbose_name="集合名称"),
                ),
                ("source_document_id", models.IntegerField(verbose_name="源文档ID")),
                ("source_chunk_index", models.IntegerField(verbose_name="源分块索引")),
                (
                    "source_app",
                    models.CharField(
                        default="pdfloader", max_length=50, verbose_name="源应用"
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(max_length=100, verbose_name="嵌入模型"),
                ),
                ("embedding_dimensions", models.IntegerField(verbose_name="嵌入维度")),
                (
                    "processing_time_ms",
                    models.FloatField(blank=True, null=True, verbose_name="处理耗时(毫秒)"),
                ),
                ("content_length", models.IntegerField(verbose_name="内容长度")),
                (
                    "page_number",
                    models.IntegerField(blank=True, null=True, verbose_name="页码"),
                ),
                (
                    "content_preview",
                    models.CharField(max_length=500, verbose_name="内容预览"),
                ),
                (
                    "document_category",
                    models.CharField(blank=True, max_length=50, verbose_name="文档分类"),
                ),
                ("tags", models.JSONField(default=list, verbose_name="标签")),
                (
                    "importance_level",
                    models.IntegerField(default=1, verbose_name="重要性等级"),
                ),
                (
                    "created_by",
                    models.CharField(blank=True, max_length=100, verbose_name="创建者"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活跃"),
                            ("archived", "已归档"),
                            ("deleted", "已删除"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后访问时间"),
                ),
            ],
            options={
                "verbose_name": "向量元数据",
                "verbose_name_plural": "向量元数据",
                "db_table": "vector_metadata",
                "indexes": [
                    models.Index(
                        fields=["source_document_id"],
                        name="vector_meta_source__7a77a0_idx",
                    ),
                    models.Index(
                        fields=["collection_name"],
                        name="vector_meta_collect_d75518_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="vector_meta_created_a802cb_idx"
                    ),
                    models.Index(
                        fields=["status"], name="vector_meta_status_0e3e6f_idx"
                    ),
                    models.Index(
                        fields=["document_category"],
                        name="vector_meta_documen_cce4b1_idx",
                    ),
                    models.Index(
                        fields=["importance_level"],
                        name="vector_meta_importa_11a1a5_idx",
                    ),
                ],
                "unique_together": {("vector_id", "collection_name")},
            },
        ),
    ]
